function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(ArgParse.usage_string, (ArgParse.ArgParseSettings,))
    precompile(ArgParse.call, (Array{Any, 1}, Type{ArgParse.ArgParseSettings},))
    precompile(ArgParse.import_settings, (ArgParse.ArgParseSettings, ArgParse.ArgParseSettings, Bool,))
    precompile(ArgParse.override_duplicates, (Array{ArgParse.ArgParseField, 1}, ArgParse.ArgParseField,))
    precompile(ArgParse.parse1_optarg, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, String, String,))
    precompile(ArgParse.check_conflicts_with_commands, (ArgParse.ArgParseSettings, ArgParse.ArgParseField, Bool,))
    precompile(ArgParse.parse1_optarg, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, Void, String,))
    precompile(ArgParse.parse1_optarg, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, Void, String,))
    precompile(ArgParse.parse1_optarg, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, String, String,))
    precompile(ArgParse.parse1_optarg, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, String, String,))
    precompile(ArgParse.parse1_optarg, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, String, String,))
    precompile(ArgParse.parse_short_opt, (ArgParse.ParserState, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse_args_unhandled, (Array{String, 1}, ArgParse.ArgParseSettings, Bool,))
    precompile(ArgParse.parse_args_unhandled, (Array{Any, 1}, ArgParse.ArgParseSettings, Bool,))
    precompile(ArgParse.parse_args_unhandled, (Array{String, 1}, ArgParse.ArgParseSettings, Bool,))
    precompile(ArgParse.check_for_duplicates, (Array{ArgParse.ArgParseField, 1}, ArgParse.ArgParseField,))
    precompile(ArgParse.merge_commands, (Array{ArgParse.ArgParseField, 1}, Array{ArgParse.ArgParseField, 1},))
    precompile(ArgParse.preparse, (ArgParse.ParserState, ArgParse.ArgParseSettings,))
    precompile(ArgParse.gen_help_text, (ArgParse.ArgParseField, ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_short_opt_name, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse_long_opt, (ArgParse.ParserState, ArgParse.ArgParseSettings,))
    precompile(ArgParse.convert_to_symbols, (Base.Dict{AbstractString, Any},))
    precompile(ArgParse.call, (Type{ArgParse.ParserState}, Array{String, 1}, ArgParse.ArgParseSettings, Bool,))
    precompile(ArgParse.call, (Type{ArgParse.ParserState}, Array{String, 1}, ArgParse.ArgParseSettings, Bool,))
    precompile(ArgParse.call, (Type{ArgParse.ParserState}, Array{Any, 1}, ArgParse.ArgParseSettings, Bool,))
    precompile(ArgParse.check_settings_can_use_symbols, (ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_name_format, (Array{String, 1},))
    precompile(ArgParse.check_settings_are_compatible, (ArgParse.ArgParseSettings, ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_short_opt_name, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.print_group, (Base.AbstractIOBuffer{Array{UInt8, 1}}, Array{Any, 1}, String, Int64, Int64, String, String, String,))
    precompile(ArgParse.check_range_default_multi2, (Array{Any, 1}, Function,))
    precompile(ArgParse.name_to_fieldnames, (Array{String, 1}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse_args, (Array{Any, 1}, Array{String, 1}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.add_command, (ArgParse.ArgParseSettings, String, String, Bool,))
    precompile(ArgParse.looks_like_an_option, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse1_flag, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, Bool, String,))
    precompile(ArgParse.check_range_default_multi2, (Array{Array{Int64, 1}, 1}, Function,))
    precompile(ArgParse.show_help, (Array{Any, 1}, Base.AbstractIOBuffer{Array{UInt8, 1}}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.show_version, (Array{Any, 1}, Base.AbstractIOBuffer{Array{UInt8, 1}}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse_arg, (ArgParse.ParserState, ArgParse.ArgParseSettings,))
    precompile(ArgParse.name_to_fieldnames, (Array{String, 1}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_arg_name, (String,))
    precompile(ArgParse.check_name_format, (String,))
    precompile(ArgParse.looks_like_an_option, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_long_opt_name, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_range_default_multi, (Array{Int64, 1}, Function,))
    precompile(ArgParse.parse1_flag, (ArgParse.ParserState, ArgParse.ArgParseSettings, ArgParse.ArgParseField, Bool, String,))
    precompile(ArgParse.check_range_default_multi, (Array{Float64, 1}, Function,))
    precompile(ArgParse.get_group, (String, ArgParse.ArgParseField, ArgParse.ArgParseSettings,))
    precompile(ArgParse.set_default_arg_group, (ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.check_long_opt_name, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.override_conflicts_with_commands, (ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.call, (Array{Any, 1}, Type{ArgParse.ArgParseSettings}, String, Bool,))
    precompile(ArgParse.name_to_fieldnames, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_range_default_multi, (Array{Any, 1}, Function,))
    precompile(ArgParse.check_arg_makes_sense, (ArgParse.ArgParseSettings, ArgParse.ArgParseField,))
    precompile(ArgParse.check_name_format, (String,))
    precompile(ArgParse.check_name_format, (Array{String, 1},))
    precompile(ArgParse.add_arg_field, (Array{Any, 1}, ArgParse.ArgParseSettings, Array{String, 1},))
    precompile(ArgParse.test_required_args, (ArgParse.ArgParseSettings, Base.Set{AbstractString},))
    precompile(ArgParse.add_arg_field, (Array{Any, 1}, ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.call, (Type{ArgParse.ArgParseSettings},))
    precompile(ArgParse.check_metavar, (String,))
    precompile(ArgParse.check_metavar, (String,))
    precompile(ArgParse.call, (Array{Any, 1}, Type{ArgParse.ArgParseSettings}, String,))
    precompile(ArgParse.parse_command_args, (ArgParse.ParserState, ArgParse.ArgParseSettings,))
    precompile(ArgParse.add_arg_field, (Array{Any, 1}, ArgParse.ArgParseSettings, Array{String, 1},))
    precompile(ArgParse.add_arg_field, (Array{Any, 1}, ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.name_to_fieldnames, (String, ArgParse.ArgParseSettings,))
    precompile(ArgParse.check_nargs_and_action, (ArgParse.ArgConsumerType, Symbol,))
    precompile(ArgParse.auto_dest_name, (String, Array{AbstractString, 1}, Array{AbstractString, 1}, Bool,))
    precompile(ArgParse.check_range_default, (String, Function,))
    precompile(ArgParse.warn_extra_opts, (Array{Symbol, 1}, Array{Symbol, 1},))
    precompile(ArgParse.fix_commands_fields, (Array{ArgParse.ArgParseField, 1},))
    precompile(ArgParse.check_range_default, (Int64, Function,))
    precompile(ArgParse.check_range_default, (Float64, Function,))
    precompile(ArgParse.check_conflicts_with_commands, (ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.check_range_default, (Array{Int64, 1}, Function,))
    precompile(ArgParse.has_cmd, (ArgParse.ArgParseSettings,))
    precompile(ArgParse.get_cmd_prog_hint, (ArgParse.ArgParseField,))
    precompile(ArgParse.check_group_name, (String,))
    precompile(ArgParse.test_range, (Function, String, String,))
    precompile(ArgParse.call, (Type{ArgParse.ArgParseTable},))
    precompile(ArgParse.test_range, (Function, Float64, String,))
    precompile(ArgParse.test_range, (Function, String, String,))
    precompile(ArgParse.test_range, (Function, String, String,))
    precompile(ArgParse.test_range, (Function, Int64, String,))
    precompile(ArgParse.test_range, (Function, String, String,))
    precompile(ArgParse.test_range, (Function, Int64, String,))
    precompile(ArgParse.parse_item, (Type{Array{Int64, 1}}, String,))
    precompile(ArgParse.test_range, (Function, Array{Int64, 1}, String,))
    precompile(ArgParse.parse_item, (Type{Float64}, String,))
    precompile(ArgParse.check_dest_name, (String,))
    precompile(ArgParse.is_arg, (ArgParse.ArgParseField,))
    precompile(ArgParse.idstring, (ArgParse.ArgParseField,))
    precompile(ArgParse.check_arg_name, (String,))
    precompile(ArgParse.is_multi_nargs, (ArgParse.ArgConsumerType,))
    precompile(ArgParse.call, (Type{ArgParse.ArgConsumerType}, Symbol,))
    precompile(ArgParse.call, (Type{ArgParse.ArgConsumerType}, Int64,))
    precompile(ArgParse.parse_item, (Type{Int64}, String,))
    precompile(ArgParse._add_arg_group, (ArgParse.ArgParseSettings, String, String, Bool,))
    precompile(ArgParse.getindex, (ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.check_action_is_valid, (Symbol,))
    precompile(ArgParse.println_unnbsp, (Base.AbstractIOBuffer{Array{UInt8, 1}}, String, Vararg{String},))
    precompile(ArgParse.println_unnbsp, (Base.AbstractIOBuffer{Array{UInt8, 1}}, String, Vararg{String},))
    precompile(ArgParse.argparse_error, (String, Vararg{Any},))
    precompile(ArgParse.auto_metavar, (String, Bool,))
    precompile(ArgParse.is_flag_action, (Symbol,))
    precompile(ArgParse.call, (Type{ArgParse.ArgConsumerType}, Char,))
    precompile(ArgParse.is_command_action, (Symbol,))
    precompile(ArgParse.add_arg_group, (ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.argparse_error, (String, Vararg{String},))
    precompile(ArgParse.haskey, (ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.argparse_error, (String, Vararg{String},))
    precompile(ArgParse.default_action, (ArgParse.ArgConsumerType,))
    precompile(ArgParse.debug_handler, (ArgParse.ArgParseSettings, ArgParse.ArgParseError,))
    precompile(ArgParse.setindex!, (ArgParse.ArgParseSettings, ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.get_group_name, (String, ArgParse.ArgParseField, ArgParse.ArgParseSettings,))
    precompile(ArgParse.add_arg_field, (ArgParse.ArgParseSettings, String,))
    precompile(ArgParse.add_arg_field, (ArgParse.ArgParseSettings, Array{String, 1},))
    precompile(ArgParse.add_arg_group, (ArgParse.ArgParseSettings, String, String,))
    precompile(ArgParse.default_action, (Int64,))
    precompile(ArgParse.call, (Type{ArgParse.ArgParseError}, String,))
    precompile(ArgParse.default_action, (Char,))
    precompile(ArgParse.parse_item, (Type{Any}, String,))
    precompile(ArgParse.check_range_default_multi2, (Void, Function,))
    precompile(ArgParse.check_range_default_multi, (Void, Function,))
    precompile(ArgParse.check_range_default, (Void, Function,))
    precompile(ArgParse.parse_item, (Type{AbstractString}, String,))
    precompile(ArgParse.parse_item, (Type{Any}, String,))
    precompile(ArgParse.default_action, (Symbol,))
    precompile(ArgParse.parse_item, (Type{AbstractString}, String,))
    precompile(ArgParse.import_settings, (ArgParse.ArgParseSettings, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse_args, (Array{String, 1}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse_args, (Array{String, 1}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.parse_args, (Array{Any, 1}, ArgParse.ArgParseSettings,))
    precompile(ArgParse.set_default_arg_group, (ArgParse.ArgParseSettings,))
end
